name: build-debug

defaults:
  run:
    working-directory: WinNUT_V2

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, dev-* ] # Build for dev primarily, probably don't need main...?
    paths:
    - '**.vb'
    - '**.vbproj'

env:
  DOTNET_VERSION: '4.8' # The .NET SDK version to use
  SLN_FILE: WinNUT_V2.sln
  DEBUG_OUTPUT: WinNUT_V2/WinNUT-Client/bin/Debug

jobs:
  build:

    name: debug-build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # Should have MSBuild.
    steps:
    # Make MSBuild available from $PATH.
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Checkout Code
      uses: actions/checkout@v4

    # msbuild cannot handle .vdproj Installer projects, so only build debug for now.
    - name: Build solution
      run: msbuild -t:build -restore -p:Configuration=Debug $env:SLN_FILE

    # For now, let msbuild continue autogenerating assembly versions and base everything off of that.
    - name: Get AssemblyVersion generated by msbuild
      id: getversion
      uses: berglie/assembly-version/get@v1
      with:
        directory: ${{ env.DEBUG_OUTPUT }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ format('WinNUT-Client-debugbuild-v{0}', steps.getversion.outputs.version) }}
        if-no-files-found: error
        path: ${{ env.DEBUG_OUTPUT }}
          
